### ISSUE TITLE
Connect to Msql in container from host

### ISSUE THREAD

**Issue by imyque** [nlzet/docker-lemp-stack#7]
Hello,

Thanks for this image and the others. 

Please, how can I connect to the mysql container from my host machine? When I tried to use Sequel Pro, got: Unable to connect to host 127.0.0.1, or the request timed out.

Secondly, how do connect an app from one container to a database in the mysql container?

Is there a way to add phpmyadmin to the stack?

Thanks

**Comment by imyque** [comment]
To answer the second question: use "mariadb" as the hostname from other containers, where "mariadb" is the name of the database container.

To answer the third question add the following snippet to the bottom of the docker compose file:

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mariadb
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=pass
  ports: 
    - "8080:80"
  links:
    - mariadb
  volumes:
    - /sessions
  restart: always

**Comment by nlzet** [comment]
@imyque Hi, I'm sorry I missed this issue. Is this still relevant ?

When your whole stack is up, you should be able to connect to localhost on port 3306. To connect from another container, make sure it is linked (docker link, done in compose file) and then it can be accessed by the container name "mariadb"). Since you mentioned Sequel pro, I suppose you are on a Mac. Are you running docker native, or are you running it in a VM? If it is a VM you shouldn't use localhost, but your machine IP. (Look into https://passingcuriosity.com/2013/dnsmasq-dev-osx/)

Regarding phpmyadmin, there are some very simple phpmyadmin containers which could be easily added in the compose file (https://hub.docker.com/r/phpmyadmin/phpmyadmin/), PR is welcome.
