### ISSUE TITLE
Make deleted all images and containers

### ISSUE THREAD

**Issue by Padrio** [nlzet/docker-lemp-stack#8]
Your makefile literally kills all containers and images by just executing make:
With all i mean all. I've got traefik & gitlab running, too. All we're gone. Thats inacceptable!

**Comment by nlzet** [comment]
Which Makefile command are you using?

For example `up_prod` translates to `$(BIN_DOCKER_COMPOSE) -f $(COMPOSE_FILE_UP_PRODUCTION) up -d` which should not kill containers. But, the behaviour of docker-compose, makes sure that containers that are related to a container that needs to be restarted/created will be restarted too (but not killed)

**Comment by Padrio** [comment]
This happen by running `make` without any parameters.

**Comment by nlzet** [comment]
Thanks, I didn't notice that indeed. It now defaulted to the clear task, because it was on top in the Makefile.

I changed it now in this commit https://github.com/nlzet/docker-lemp-stack/commit/f10ca8740a745c2ecbf1e1671672de255225fa75

The default task is now to build the services defined in the compose-file. I didn't point it to the "up" task, because it depends wether your want to run in dev or prod.

You may re-open this issue if this doesn't solve your problem.
